name: Utc App CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

env:
  python_version: "3.11"
  IMAGE_NAME: "my-portfolio-2"
  AWS_REGION: "env.AWS_REGION"

jobs:
  build:
    runs-on: ubuntu-latest

    # Job-level env (can access secrets)
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest test.py

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

        # Docker image build
      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .

      # Install Trivy
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          version: latest

      # Scan the built image
      - name: Scan Image with Trivy
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE

      # Push to ECR
      - name: Push Image to ECR
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          docker push $IMAGE
